#logging:
#    level:
##       打印sql，需要将logging.level指向dao的位置
#       com.rogchen.springRogchen.mapper: debug

spring:
    application:
        name: ylzinfo-cloud-feignDemo-rogchen
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
server:
    port: 28801


eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://192.168.44.56:8080/eureka/
#            defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
