logging:
    level:
#       打印sql，需要将logging.level指向dao的位置
       com.rogchen.www.mybatis.mapper: debug

spring:
    application:
        name: ylzinfo-cloud-mybatisDemo-rogchen
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: cloud_demo
        url: jdbc:mysql://localhost:3306/cloud_demo?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


server:
    port: 48801


eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://192.168.44.56:8080/eureka/
#            defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


# 配置数据库
mybatis:
    basepackage: com.rogchen.www.mybatis.mapper
    xmlLocation: classpath:mapper/**/*.xml
#    configLocation: classpath:config/mybatis-config.xml
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count:
      countSql