server.port: 8888 #启动端口
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    service-url:
       defaultZone: http://192.168.44.56:8080/eureka/

spring:
  application:
    name: cloud-config-rogchen
#  profiles:
#    active: native
  cloud:
    config:
      server:
         git:
           uri: https://github.com/forezp/SpringcloudConfig/
           searchPaths: respo
           username:
           password:
      label: master
#    bus:
#      trace:
#        enabled: true # 开启跟踪总线事件
#  rabbitmq:
#    host: 192.168.44.56
#    port: 5672
#    username: hxb
#    password: hxb
#
#security:
#  user:
#    name: user
#    password: ${CONFIG_SERVER_PASSWORD:password}
#
#management:
#  security:
#     enabled: false
