logging:
    level:
#       打印sql，需要将logging.level指向dao的位置
       com.rogchen.springRogchen.mapper: debug

spring:
    application:
        name: ylzinfo-cloud-otherDemo-rogchen
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

server:
    port: 18801
