server.port: 8888eureka
spring:
  application:
    name: cloud-config-rogchen
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
     enabled: false
#security:
#  user:
#    name: user
#    password: ${CONFIG_SERVER_PASSWORD:password}
#